### ISSUE TITLE
Adapting to NextCloud 11+

### ISSUE THREAD

**Issue by putt1ck** [Patt92/Workin2Gether#9]
Have used this app in OwnCloud installations and have a client using NC (10, soon to be 11) who would be interested in this sort of functionality. Has the possibility of adapting this to NC11 been looked at?

**Comment by Patt92** [comment]
Hello putt1ck,

Ofcourse it will be adapted to NC. 
I was staying on OC for a long time. I've set up my development envoirnment for Nextcloud in the last days.
I will create the release for NC 10+11 soon, once I update the server of my company.

Maybe I'll get it done this weekend, because I miss it at my private server, which is currently NC10 :-)

**Comment by putt1ck** [comment]
Great news. Let me know how we can help. :)

**Comment by Patt92** [comment]
Current release supporting Nextcloud. I somehow got stuck at the publishing process on the Nextcloud end... I think I'll be able to upload it in a day to their store. 
https://github.com/Patt92/Workin2Gether/releases/tag/0.9.0.1 will work on Nextcloud 10/11. Grab the tar.gz and install it manually for prechecking it.

**Comment by putt1ck** [comment]
Great, will give it a go.

**Comment by putt1ck** [comment]
Stream of consciousness feedback:
- should tar contents be owned by root?
- in settings/apps it say the app is "_by  [object Object]_"
- "file not locked" and "locked by username" locate differently on the bar - caused by the sharing and context menu icons disappearing. Can see why sharing should not be changeable when locked, but icon could still appear, and entirely possible that comments for a locked item would still be useful (both old and new)

**Comment by Patt92** [comment]
To 1st:Tar contents obviously shouldn't be owned by root. That's normal, if you untar it with the user root.
Chown it with your web user.
Permissions aren't set in any files, because they are compressed with windows.

To 2nd:
Where is it shown, I don't see that error.
![settings_app](https://cloud.githubusercontent.com/assets/6998914/22299411/48eccb0a-e324-11e6-8b93-d8ea17294c2d.PNG)
![apps_activated](https://cloud.githubusercontent.com/assets/6998914/22299412/48ecf5e4-e324-11e6-9587-ddb66fc71217.PNG)

To 3rd:
That's a layout issue, because it's aligned on the right side. I guess it would be possible to add a padding by the same size, the icons used before, but I don't think it's best practice to do so.

**Comment by putt1ck** [comment]
Ref  [object Object]
it appears in the info for the app when you access the apps area as an admin
![image](https://cloud.githubusercontent.com/assets/2872580/22304819/049b5202-e331-11e6-9782-41ae5a487baa.png)
That particular test server is running 10.03

**Comment by putt1ck** [comment]
Regarding the shift from lock/unlock - it wouldn't move if the other icons were retained when the object was locked - do they have to be removed when the file is marked as locked?

**Comment by Patt92** [comment]
To the display with by [object Object]: This is related to Nextcloud servers, running version 10-10.0.x
refer to https://github.com/nextcloud/calendar/issues/199. This is not app related. In Nextcloud 11 it's working fine.

Removing the icons was the intention. 
The layout will be fixed, once I try implementing some way of layout like https://github.com/Patt92/Workin2Gether/issues/5 

for fixing the different alignment at least on page load, simply append 
`a.w2g_active{padding-right:60px !important;}`
to files_w2g/css/styles.css

**Comment by putt1ck** [comment]
Anything I can do to help get your app available in the NextCloud App Store?

**Comment by Patt92** [comment]
Thanks, everything fine. Currently only depending on my spare time. Will be this week soon.

**Comment by putt1ck** [comment]
Got a client deployment where they really want this feature - sure there's nothing I can do to help?

**Comment by Patt92** [comment]
Would be great, but I don't know where to start for invoking the webdav call of the client. It's not really easy to find out without the necessary documentation. When OC changed to bubble menus, it was the same. If you know how to overwrite the webdav upload handler on a app level, it'd be great. As far as I know apps are not accessed at this point. If this is the case, it would be only possible to apply the changes on the bare code, which will cause integrity issues and loss on updates. Tell me, if you know another way to approach

**Comment by putt1ck** [comment]
I'll ask... 

But implication is the lock (document "check out") feature belongs in core rather than an app?

**Comment by Patt92** [comment]
for the standalone client yes. I don't know if we're talking about the same thing. We are talking about the sync client wright? Because of your client deployment. 

I didn't see any hint to interact with the webdav endpoint for apps (sync client).
Or did you mean the Nextcloud support?

**Comment by putt1ck** [comment]
My client deployment would be happy with a "none-foolproof" lock file in web UI function as currently achieved - which to be fair is about all any web-based doc manager can depend on, unless you can force people not to download files. As soon as a file is downloaded someone can be editing it independently of the system anyway, so potential versioning conflicts arise - which I think the sync client can already alert users about, so that's not much different.

But the client is interested in stability & reduced lock-in and so would be more comfortable with the app being "officially" available from the Nextcloud app store rather than independent, regardless of functionality.

**Comment by Patt92** [comment]
That is at this point impossible. This would require changes in the core.
The web UI also has the limitation to overwrite the listeners. The dev couldn't find out any way to interact with it.

**Comment by putt1ck** [comment]
The web UI "visibly locked" is a step up from where Nextcloud is now.

**Comment by greavette** [comment]
Hello @Patt92 , forgive me for sticking my nose into an issue you both are working hard to solve with Crhis...just wanted to understand where this issue was going.

I too have a need to use Workin2Gether in our office whereby I'd like to have the ability for our secretaries to put a visible lock a file in the web client (not webdav or any other view) of Nextcloud 11.  I had installed your app in an early version of ownCloud and remembered that it would be a very useful app to have.  

Please clarify for me if this ability to list a file as being locked (therefore in use) within the Nextcloud browser can be implemented...or are you saying that this is not possible now?  

Perhaps my use case differs from Chris so I don't want to interrupt his requirements with mine.  I've been watching this issue in hopes that I can install this app on my Nextcloud 11 and I'd like to confirm that this will still be possible or not possible.

Thank you.

**Comment by putt1ck** [comment]
@greavette my use case at the base is the same - just to prevent centrally maintained files from being edited by someone else when they are being updated, and that the sync client won't be used for edits of those files (and users of the sync client will be made aware through training what file classes they should freely edit and which they shouldn't).

Of course, it would be nice if the file lock also worked with sync client - but that probably needs interaction with the sync client team.

**Comment by greavette** [comment]
Thank you @putt1ck for confirming your use case.  Good to see that we both need the same functionality from this App.  I agree that it would be nice if the file lock worked with sync clients but in our small office just having a visual for the secretaries to see that a file is locked on the Web Client for Nextcloud is enough for us.  

Looking forward to @Patt92 answer on if this is still possible for Nextcloud 11 being added to the app store (and ideally not being an experimental app).  

Thank you.

**Comment by Patt92** [comment]
Proudly announcing the public release in the Nextcloud store :-)
